"""followers

Revision ID: 926ca8bf135c
Revises: 70c8886ab311
Create Date: 2018-06-24 18:29:06.811525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '926ca8bf135c'
down_revision = '70c8886ab311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('following_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.create_foreign_key(None, 'followers', 'user', ['following_id'], ['id'])
    op.drop_column('followers', 'followed_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('followed_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.create_foreign_key(None, 'followers', 'user', ['followed_id'], ['id'])
    op.drop_column('followers', 'following_id')
    # ### end Alembic commands ###
